### ISSUE TITLE
Non issue related

### ISSUE THREAD

**Issue by seanamor** [FountainMC/FountainForge#8]
Just wanted to get info on this project, I could not find documentation. Just saw a comment on a recent forum mentioning the project. What is it? What will it do? Will it make spigot compatible with sponge/forge?

**Comment by jamierocks** [comment]
EDIT: I thought this was an issue on Waterfall -_-

**Comment by phase** [comment]
> Just saw a comment on a recent forum mentioning the project. 

:o What forum?

> What is it?

Minecraft Service Mod API

> What will it do?

Give Java developers an API around the Minecraft Server.

> Will it make spigot compatible with sponge/forge?

Um.... no... not even close... It's a _new_ API. There have been ideas for Bukkit compatibility, but nothing is concrete yet.

**Comment by Techcable** [comment]
Its a new API designed to replace sponge and bukkit https://fountainmc.org/
